export interface Word {
    welsh: string;
    english: string;
    type?: 'noun' | 'verb' | 'adjective' | 'phrase';
    group?: 'greeting' | 'questions' | 'responses' | 'people' | 'school' | 'food' | 'animals' | 'weather' | 'time' | 'feelings' | 'actions';
}

export const words: Word[] = [
  { welsh: "bore da", english: "good morning", type: 'phrase', group: 'greeting' },
  { welsh: "prynhawn da", english: "good afternoon", type: 'phrase', group: 'greeting' },
  { welsh: "nos da", english: "good night", type: 'phrase', group: 'greeting' },
  { welsh: "noswaith dda", english: "good evening", type: 'phrase', group: 'greeting' },
  { welsh: "sut wyt ti?", english: "how are you?", type: 'phrase', group: 'questions' },
  { welsh: "da iawn", english: "very good", type: 'phrase', group: 'responses' },
  { welsh: "croeso", english: "welcome", type: 'phrase', group: 'greeting' },
  { welsh: "diolch", english: "thank you", type: 'phrase', group: 'responses' },
  { welsh: "os gweli di'n dda", english: "please", type: 'phrase', group: 'responses' },
  { welsh: "ie", english: "yes", type: 'phrase', group: 'responses' },
  { welsh: "nage", english: "no", type: 'phrase', group: 'responses' },
  { welsh: "hwyl fawr", english: "goodbye", type: 'phrase', group: 'greeting' },
  { welsh: "tan y tro nesa", english: "until next time", type: 'phrase', group: 'greeting' },
  { welsh: "ble wyt ti'n byw?", english: "where do you live?", type: 'phrase', group: 'questions' },
  { welsh: "dw i'n byw yn...", english: "I live in...", type: 'phrase', group: 'responses' },
  { welsh: "be' sy?", english: "what's up?", type: 'phrase', group: 'questions' },
  { welsh: "beth wyt ti'n neud?", english: "what are you doing?", type: 'phrase', group: 'questions' },
  { welsh: "dw i'n hoffi", english: "I like", type: 'phrase', group: 'feelings' },
  { welsh: "dw i ddim yn hoffi", english: "I don't like", type: 'phrase', group: 'feelings' },
  { welsh: "dw i'n mynd", english: "I'm going", type: 'phrase', group: 'actions' },
  { welsh: "wyt ti'n iawn?", english: "are you okay?", type: 'phrase', group: 'questions' },
  { welsh: "caru", english: "to love", type: 'verb', group: 'feelings' },
  { welsh: "cariad", english: "love / darling", type: 'noun', group: 'feelings' },
  { welsh: "teulu", english: "family", type: 'noun', group: 'people' },
  { welsh: "ysgol", english: "school", type: 'noun', group: 'school' },
  { welsh: "ysgol gynradd", english: "primary school", type: 'noun', group: 'school' },
  { welsh: "ysgol uwchradd", english: "secondary school", type: 'noun', group: 'school' },
  { welsh: "afal", english: "apple", type: 'noun', group: 'food' },
  { welsh: "bara", english: "bread", type: 'noun', group: 'food' },
  { welsh: "caws", english: "cheese", type: 'noun', group: 'food' },
  { welsh: "dŵr", english: "water", type: 'noun', group: 'food' },
  { welsh: "coffi", english: "coffee", type: 'noun', group: 'food' },
  { welsh: "llefrith", english: "milk", type: 'noun', group: 'food' },
  { welsh: "te", english: "tea", type: 'noun', group: 'food' },
  { welsh: "paned", english: "cup (of tea)", type: 'noun', group: 'food' },
  { welsh: "ci", english: "dog", type: 'noun', group: 'animals' },
  { welsh: "cath", english: "cat", type: 'noun', group: 'animals' },
  { welsh: "tywydd", english: "weather", type: 'noun', group: 'weather' },
  { welsh: "haul", english: "sun", type: 'noun', group: 'weather' },
  { welsh: "glaw", english: "rain", type: 'noun', group: 'weather' },
  { welsh: "eira", english: "snow", type: 'noun', group: 'weather' },
  { welsh: "awel", english: "breeze", type: 'noun', group: 'weather' },
  { welsh: "rhew", english: "frost/ice", type: 'noun', group: 'weather' },
  { welsh: "heno", english: "tonight", type: 'noun', group: 'time' },
  { welsh: "heddiw", english: "today", type: 'noun', group: 'time' },
  { welsh: "ddoe", english: "yesterday", type: 'noun', group: 'time' },
  { welsh: "fory", english: "tomorrow", type: 'noun', group: 'time' },
  { welsh: "enaid", english: "soul", type: 'noun', group: 'feelings' },
  { welsh: "babi", english: "baby", type: 'noun', group: 'people' },
  { welsh: "bachgen", english: "boy", type: 'noun', group: 'people' },
  { welsh: "merch", english: "girl", type: 'noun', group: 'people' },
  { welsh: "dyn", english: "man", type: 'noun', group: 'people' },
  { welsh: "menyw", english: "woman", type: 'noun', group: 'people' },
  { welsh: "cysgu", english: "to sleep", type: 'verb', group: 'actions' },
  { welsh: "deffro", english: "to wake up", type: 'verb', group: 'actions' },
  { welsh: "cerdded", english: "to walk", type: 'verb', group: 'actions' },
  { welsh: "rhedeg", english: "to run", type: 'verb', group: 'actions' },
  { welsh: "bwyta", english: "to eat", type: 'verb', group: 'actions' },
  { welsh: "yfed", english: "to drink", type: 'verb', group: 'actions' },
  { welsh: "chwarae", english: "to play", type: 'verb', group: 'actions' },
  { welsh: "gweithio", english: "to work", type: 'verb', group: 'actions' },
  { welsh: "mynd", english: "to go", type: 'verb', group: 'actions' },
  { welsh: "dod", english: "to come", type: 'verb', group: 'actions' },
  { welsh: "gweld", english: "to see", type: 'verb', group: 'actions' },
  { welsh: "clywed", english: "to hear", type: 'verb', group: 'actions' },
];
